import Head from "next/head";
import Script from "next/script";
import Navbar from "../components/Navbar/Navbar";
import Auth from "./accounts/auth/[authType]";
export default function Home(){
return (
    <div>
        <Head>
            <title> InstaClone | TimeLine</title>
            <meta

            name="description"
            content="Generated by create next app & firebase"
             />

            <Script src="https://cdn.onesignal.com/sdks/OneSignalSDK.js" />
             <link rel="icon" href="/favicon.ico" />
        </Head>
        <Navbar/>
        <Auth/>
    </div>
)

}